### ISSUE TITLE
Enum all the things: Storyboards, Segues, Images not in xcassets

### ISSUE THREAD

**Issue by AndrewSB** [kaandedeoglu/Shark#1]
Wondering if you had run into [this similar project](https://github.com/mac-cain13/R.swift). Any thoughts on implementing similar functionality in Shark?

**Comment by kaandedeoglu** [comment]
Hi!

Yes I've seen it a few weeks back, it's definitely more comprehensive than what we have here. I kind of want Shark to do one thing only but do it good, which is images and assets. Although parsing images not in xcassets is a great idea!

I'm planning on introducing command line options that can change the behavior (like disabling nesting of enums, or changing the top level Enum name etc..). Unfortunately [OptionKit](https://github.com/nomothetis/OptionKit) is outdated and doesn't support Swift 2.0, I either have to wait for an update/alternative or roll my own :) That being said, pull requests are always more than welcome.
