### ISSUE TITLE
Please support Framework target 

### ISSUE THREAD

**Issue by quangDecember** [kaandedeoglu/Shark#14]
in line 28 of **XcodeProjectHelper.swift** ; I know you might want to eliminates Tests & Aggregate target but this eliminates SDK targets also

```swift
let applicationTargets = xcodeproj.pbxproj.nativeTargets.filter({ $0.productType == .application })
```

the generated code doesn't contain Bundle information, so it will fail for framework bundle

**Comment by kaandedeoglu** [comment]
Just released 1.1.1, it should now also work with framework targets
