### ISSUE TITLE
Shark.swift file contains invalid swift code when a particular font file is present

### ISSUE THREAD

**Issue by ghost** [kaandedeoglu/Shark#22]
I have a font file with name "Lato-Light.ttf". (https://fonts.google.com/specimen/Lato)

The code generated for this font is
```swift
public enum F {
    public static func lato-light(ofSize size: CGFloat) -> UIFont { return UIFont(name: "Lato-Light", size: size)! }
}
```

The font name contains hyphen and is invalid swift code.

P.S.- I have several other font files with hyphen in their file names. However, Shark generates correct snakeCase font names for those files. The issue is seen only for this particular font file

**Comment by kaandedeoglu** [comment]
Hey @losernobody, thank you so much for reporting! I've just released 1.3.1, you can update and hopefully it'll fix your problem. I'll be really happy if you can confirm that the bug is fixed once you've tried it out. Cheers 🥂
