### ISSUE TITLE
Run only, if necessary

### ISSUE THREAD

**Issue by mickeyl** [kaandedeoglu/Shark#25]
Great project. Lean and mean, no hidden magic, it just works!

That said, is there an easy way to run it only after the `.xcodeproj` file has been updated?

**Comment by kaandedeoglu** [comment]
Thanks, I really like using it too! 
Did you mean "only after `.strings` file has been updated" by any chance? I haven't looked into it as it's been lightning fast for the projects I used this in so far, but I wouldn't be surprised if it gets slower for huge projects. One could potentially use the `Input Files` & `Input Files List` in the run script sections, which would need some exploration 🔍

**Comment by mickeyl** [comment]
Closing this as it's probably not worth to waste time on it, since – as you said – Shark is extremely fast.

**Comment by mickeyl** [comment]
Worth a note here after 2.2.0: the runtime concern that made this interesting in the first place is gone. Shark no longer resolves Swift package manifests, and typical runs are back to 0.1s — a 5-target white-label project takes 0.11s per target, a project with eight local packages 0.11s instead of 2.85s. The dependency-file support (`--deps`) added in the meantime still lets Xcode skip Shark entirely when nothing changed.
