### ISSUE TITLE
No top-level namespace

### ISSUE THREAD

**Issue by mickeyl** [kaandedeoglu/Shark#26]
I realize I can adjust the top-level namespace with the `--name` argument and bring the namespaces into the top level area via `typealias`es, but would it be possible to get rid of the top-level namespace altogether?

**Comment by kaandedeoglu** [comment]
Hey, thanks for the feedback :) It's definitely possible. Just so I understand, you'd just want `I`, `C,` `F`, `L` enums on the global namespace right?

**Comment by mickeyl** [comment]
Yes, that would be my preference.

**Comment by mickeyl** [comment]
Amazing, thanks a lot!
