### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gsimmons** [kaandedeoglu/Shark#3]
PhaseScriptExecution Run\ Script\ -\ Shark /Users/gsimmons/Library/Developer/Xcode/DerivedData/CareConsult-etlsolxnmuijbhfkgvpwykbilvup/Build/Intermediates/CareConsult.build/Debug-iphonesimulator/CareConsult.build/Script-6DB712881BA9A9DD0031CBE7.sh
    cd /Users/gsimmons/Developer/CenseoHealth/CareConsult
    /bin/sh -c /Users/gsimmons/Library/Developer/Xcode/DerivedData/CareConsult-etlsolxnmuijbhfkgvpwykbilvup/Build/Intermediates/CareConsult.build/Debug-iphonesimulator/CareConsult.build/Script-6DB712881BA9A9DD0031CBE7.sh

/Users/gsimmons/Library/Developer/Xcode/DerivedData/CareConsult-etlsolxnmuijbhfkgvpwykbilvup/Build/Intermediates/CareConsult.build/Debug-iphonesimulator/CareConsult.build/Script-6DB712881BA9A9DD0031CBE7.sh: line 2: Creating: command not found
Command /bin/sh failed with exit code 127

**Comment by kaandedeoglu** [comment]
Hello, let's see now...

Can you please attach a screenshot of your build phase? 

Also, do you see the instruction message printed when you go to the terminal and type `shark` ?

**Comment by gsimmons** [comment]
Sorry, I meant to give more info.

The SharkImages.swift file is generated and typing shark in the terminal gets the help message, so it's running. I'm using Xcode 7 GM.

There is no error if the Assets.xcassets only has the app icon in it. If I add any images, I get the error.

![screen shot 2015-09-16 at 9 38 09 am](https://cloud.githubusercontent.com/assets/54147/9907831/90d3bc40-5c56-11e5-8bae-d4a1edda38a5.png)

**Comment by kaandedeoglu** [comment]
I've recently integrated to one of my own projects without any problems, our setup looks almost identical. Can I please ask you to clone (or pull the latest changes if you have it) Shark and run `sh setup.sh` again, and then try building again?

**Comment by kaandedeoglu** [comment]
And please get rid of the backticks surrounding your build phase body

**Comment by gsimmons** [comment]
It was the backticks. Hooray for copy / pasting too quickly.
