### ISSUE TITLE
NSDataAsset

### ISSUE THREAD

**Issue by mickeyl** [kaandedeoglu/Shark#30]
Today I learned about [NSDataAsset](https://developer.apple.com/documentation/uikit/nsdataasset), which would come in handy for, e.g. sounds, level maps, or what not. `NSDataAsset`s are also stored in the asset catalogue, so it might be cool to support them in shark.

**Comment by kaandedeoglu** [comment]
Great suggestion, let's give this a try 🚀

**Comment by kaandedeoglu** [comment]
@mickeyl Just released v1.3.5 - now we also generate a `D` enum for NSDataAssets, thanks for bringing this up 🦾

**Comment by mickeyl** [comment]
This is so cool, thanks a ton! 🎉
