### ISSUE TITLE
Storyboard support

### ISSUE THREAD

**Issue by mickeyl** [kaandedeoglu/Shark#33]
Would it be possible to add support for `enum`ifying Storyboards, e.g. accessing `Main.storyboard` as `R.S.Main`?

(I'd have a go at a pull request, if you don't have the time for it – although I would need some guidance… 😄)

**Comment by kaandedeoglu** [comment]
We can definitely look into it. It never made it into Shark because I gave up on storyboards years ago 😄 Should be quite straightforward actually

**Comment by kaandedeoglu** [comment]
@mickeyl  #34 :)

**Comment by mickeyl** [comment]
@kaandedeoglu You're my hero! Thanks very much, this works great! (While I know that the use of storyboards is quite controversial, I think that they have their strengths and I'm using them for where it makes sense).

**Comment by kaandedeoglu** [comment]
1.3.7 is out with Storyboards support, once again, thanks for requesting Mickey 🙏
