### ISSUE TITLE
Add namespaces support for Colors

### ISSUE THREAD

**Issue by bgdn0** [kaandedeoglu/Shark#35]
Hello,

Is it possible to add nested namespaces support for generated Colors enum (the same way as for Images enum) ?

**Comment by kaandedeoglu** [comment]
Hey @bgdn0 ,that's a very good suggestion, thanks for getting involved!

I'm a little concerned it'll break code for some people. On the other hand  it makes sense to align images & colors. Let's give it a try 🚀

**Comment by kaandedeoglu** [comment]
@bgdn0  So the feature is now working, we also get the nesting behavior for colors (it also uncovered a beautiful refactoring that got rid of a lot of duplicate code). That being said, it now feels a little weird for my projects that use `Shark`. 
I usually tend to put all colors into a `Colors` folder, therefore after this change we'll go from:

```swift
view.backgroundColor = C.primaryRed
```

to

```swift
view.backgroundColor = C.Colors.primaryRed
```

So I would like to hear about your use cases and whether you organize color assets per folder when building applications.

**Comment by bgdn0** [comment]
Hey @kaandedeoglu , cool, when can I expect the feature release to try it out?

We have separate Asset catalogs for Images and Colors.
Colors look something like this (simplified)

```
Colors.xcassets
	├── button
	│	├── disabled.colorset
	│	├── main.colorset
	│	└── secondary.colorset
	├── input
	│	├── active.colorset
	│	├── error.colorset
	│	├── inactive.colorset
	│	└── placeholder.colorset
	├── list
	│	├── background.colorset
	│	└── separator.colorset
	└── text
		├── error.colorset
		├── main.colorset
		└── secondary.colorset
```

and  the usage
```swift
button.backgroundColor = C.button.main
label.textColor = C.text.main
```

In one project we had colors gray1, ... gray6 and blue1, .... blue4, and it's not obvious should I use gray2 or gray4 for the text, so I prefer to name colors with something more meaningful and use namespaces

**Comment by kaandedeoglu** [comment]
Hey, the changes are now pushed to the `namespaced_color_assets` branch, you'll have to build from source to test it:

Simply navigating to the root and doing `swift build -c release --disable-sandbox` should give you an executable at `.build/release/Shark`. Happy testing 🧀

**Comment by bgdn0** [comment]
Works good for me 🎉. Thank you! 👍

If you don't want to break Colors enum compatibility with the previous version, maybe it worth to add use-namespaces-for-colors as a command line option?

**Comment by mickeyl** [comment]
Hi @bgdn0. When I started working on Shark with regards to the new framework-specific code generation, I was not aware of the `namespaced_color_assets` branch. I think it's a good idea to bring this into master before working on the next features. I have just [rebased](https://github.com/kaandedeoglu/Shark/tree/namespaced_color_assets_rebase) it. 

While working on this I noticed one gotcha… the nested namespace enum builder does not evaluate the corresponding Xcode setting yet. This can lead to confusion, hence going forward I'd rather evaluate the Xcode _Provides Namespace_ setting than providing yet another command line option:
![Bildschirmfoto 2022-09-18 um 14 17 18](https://user-images.githubusercontent.com/167469/190901709-d4cf52f9-43bb-4c5e-bc4e-dfce24dd2638.png)

I'd also rework the image support then to honor that flag.

What do you think?

**Comment by mickeyl** [comment]
This is now life as per the 1.6.0 release.
