### ISSUE TITLE
Not working with LaunchImage on xcassets

### ISSUE THREAD

**Issue by filipealva** [kaandedeoglu/Shark#4]
Hey,

It does not works when the project has a LaunchImage. It creates the following code for LaunchImage:

``` swift
public enum LaunchImage.launchimage {
}
```

which causes a build time crash.

**Comment by kaandedeoglu** [comment]
@filipealva Hey there, 
thanks for spotting that, looks like a very serious mistake on my part!

I'll fix it today and push a fix

Just to be on the same page, `Shark` will ignore all LaunchImage imagesets (as it does for AppIcon imagesets) - is that okay for you?

**Comment by filipealva** [comment]
@kaandedeoglu Nice! Yes, its ok to ignore all LaunchImage on assets.

Congrats about the project, and thank you for the fast feedback :+1:

**Comment by kaandedeoglu** [comment]
@filipealva I just released version 0.1.1 and it's ready to use through Cocoapods or manually.

I'm leaving this open until you confirm that everything works as expected. Please let me know when you try - again, thanks for reaching out :+1:

**Comment by filipealva** [comment]
@kaandedeoglu I tried right now, it is working properly!

Thanks :)
