### ISSUE TITLE
Change visibility from public

### ISSUE THREAD

**Issue by denizdogan** [kaandedeoglu/Shark#44]
Would be nice if we could change the default visibility from `public` to e.g. `internal`

**Comment by mickeyl** [comment]
We could do that. Alas, I'm not quite sure whether this would limit the usability, if you are using (local) modules in your project and have a dedicated module where your resources are included. With `internal` you would then not be able to access the resources outside of this module.

If at all, I'm rather leaning towards a command line option.

**Comment by denizdogan** [comment]
Oh, I should have clarified, I meant this as an opt-in type of thing :) The default is fine!
