### ISSUE TITLE
Build issue with XCode 7.3

### ISSUE THREAD

**Issue by krodak** [kaandedeoglu/Shark#5]
Hi,
I've been successfully using your script with XCode 7.2 and Swift 2.0

Now, after migration to new XCode 7.3, my builds with Shark run scripts are failing.

<img width="1138" alt="screen shot 2016-03-29 at 11 47 44" src="https://cloud.githubusercontent.com/assets/1955364/14099547/1aad156a-f5a4-11e5-81da-3ef0bcd96aab.png">

Build is failling with exit code 133:

<img width="1464" alt="screen shot 2016-03-29 at 11 48 31" src="https://cloud.githubusercontent.com/assets/1955364/14099562/42088e00-f5a4-11e5-978b-62d1b89b9490.png">

**Comment by kaandedeoglu** [comment]
@krodak I've rebuilt the binary with the Swift 2.2 toolchain, it should all work now after you `pod update`. Sorry for the slight delay. Please let me know if it works. Also thank you for bringing this up
